/**
 * Copyright 2021 TM9657 GmbH. All Rights Reserved.
 *
 * Loads a config file that has been generated by the our Portal.
 */

import { createRequire } from "module";
const require = createRequire(import.meta.url);
const config = require("./config.json");
declare global {
  type config = {
    API: string;
    SECRET: string;
    DEFAULT_PATH: string;
    FETCH_DELAY: number;
    API_ROUTE: string;
    TORRENT_ANNOUNCES: string[];
    SOCKET: string;
    ICE: [];
    USER: string;
  };
}

let save_path_absolute = ".";

if (typeof process.env.DEFAULT_PATH !== "undefined") {
  save_path_absolute = process.env.DEFAULT_PATH;
}

export default {
  API: config.api,
  SECRET: config.secret,
  DEFAULT_PATH: save_path_absolute,
  //only allow fetch rate of 60 seconds or higher (otherwise your server will be removed from our system)
  //irrelevant in the current implementation.
  FETCH_DELAY:
    config.fetch_delay_sec >= 60 ? config.fetch_delay_sec * 1000 : 60000,
  API_ROUTE: config.route,
  SOCKET: config.websocket,
  TORRENT_ANNOUNCES: config.announces,
  ICE: config.ice,
  USER: config.user,
};
